version: 0.2

phases:
  install:
    commands:
      - npm install        # Install dependencies
  build:
    commands:
      - docker build -t my-image .
      - echo '[{"name":"my-container","imageUri":"my-account-id.dkr.ecr.us-east-1.amazonaws.com/my-repo:latest"}]' > imagedefinitions.json

artifacts:
  files:
    - '**/*'               # Include all files
    - imagedefinitions.json # Ensure imagedefinitions.json is included as an artifact
