version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - echo '[{"name":"my-container","imageUri":"my-account-id.dkr.ecr.us-east-1.amazonaws.com/my-repo:latest"}]' > imagedefinitions.json
artifacts:
  files:
    - '**/*'
