version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - echo '[{"name":"democontainer","imageUri":"039289871235.dkr.ecr.us-east-1.amazonaws.com/my_demo_repo_2"}]' > imagedefinitions.json
artifacts:
  files:
    - '**/*'
